DM-27859 Test coadd PSF quality by direct subtraction of single source in template coadd image
lsst-dm/diffimTests pull request #16
Opened 2021-01-05 06:28 UTC by kgabor

2021-01-07 22:29 UTC, isullivan requested changes
Please replace the `%run -n -i "subtraction_defs.py"` calls in your notebooks with explicit imports and calls to the functions you are using.
The `psf_direct_subtraction_gen2_decam_coadd.ipynb` notebook looks fine, but I am concerned about the results you show in `psf_direct_subtraction_gen3_hsc_coadd.ipynb`. It looks like there are significant residuals even for sources that look completely isolated in the thumbnails, and that needs to be investigated before we can close this ticket.

2021-01-07 22:29 UTC, isullivan commented on tickets/DM-27859_psf_subtraction_coadd/subtraction_defs.py
> +    -------
Add the definition of the return value.

2021-01-07 22:29 UTC, isullivan commented on tickets/DM-27859_psf_subtraction_coadd/subtraction_defs.py
> +    psfCenter = geom.Point2D(srcCat['base_SdssCentroid_x'],
Would `srcCat.getX()` and `srcCat.getY()` work here?

2021-01-07 22:29 UTC, isullivan commented on tickets/DM-27859_psf_subtraction_coadd/subtraction_defs.py
> +    srcCat : `lsst.afw.table.SourceRecord'`
Here and elsewhere: maybe call this `srcRec` or something similar, since it's only a single source and not a catalog.

2021-03-03 08:48 UTC, kgabor commented on tickets/DM-27859_psf_subtraction_coadd/subtraction_defs.py
> +    psfCenter = geom.Point2D(srcCat['base_SdssCentroid_x'],
Thanks for pointing this out. I wasn't very familiar with the slot + name mapping mechanism. Actually `psfCenter = srcCat.getCentroid()` would be even more compact.  
Though in this case, I think, it's clearer to keep the explicit field names given that we have multiple centroids calculated.

2021-03-04 04:17 UTC, merged